### ISSUE TITLE
'GUI_cSPider.fig' file missing?

### ISSUE THREAD

**Issue by TonyR85** [wilkesk/cSPider#1]
Hello,

Thank you for creating cSPider! It looks great!
I've tried to run it in Matlab R2015b by following the different steps of the User Guide but it gives me an error for Step 2 when I run 'Run_automatic_CSP_determination.m'.
I don't have any GUI that opens and Matlab says:

**Error using load
Unable to read file 'GUI_cSPider.fig'. No such file or directory.

Error in matlab.graphics.internal.figfile.FigFile/read (line 31)
hgDataVars = load(filename, '-mat', '-regexp', '^hg[M]');

Error in matlab.graphics.internal.figfile.FigFile

Error in hgload (line 50)
FF = matlab.graphics.internal.figfile.FigFile(filename);

Error in matlab.hg.internal.openfigLegacy (line 57)
    [fig, savedvisible] = hgload(filename, struct('Visible','off'));

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 158)
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);

Error in GUI_cSPider (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in Run_automatic_CSP_determination (line 8)
GUI_cSPider**

Am I missing a step?
Thanks.

**Comment by wilkesk** [comment]
Hey TonyR85,
thanks for notifying me! I've uploaded the missing file. It should work now. Tell me if there are any other issues. Have a nice day.

Cheers,
Skadi
